
compile:
	        vlib work;
					              vlog -sv event_pool.sv

simulate:
	        vsim event_pool_ex -l event_pool.log -c -do "run -all; exit;"

all:
	        clear;
					              vlog -sv event_ pool.sv
										    vsim event_pool_ex  -l event_pool.log -c -do "run -all; exit;"

clear:
	        clear
